### PR TITLE
feat: add Dockerfile

### PR DESCRIPTION
**Pull request by fbertetto**
Adding a Dockerfile in order to make it easier to reproduce the environment.

It works without any extra parameters just `docker build -t <image_name> . `

### CODE REVIEW

**Comment by fbertetto** [comment]
@DavidOgunsAWS what do you think about this one ?

**Comment by t04glovern** [comment]
This worked great for me, thanks for posting.

**Comment by MohMaz** [comment]
I think it'll be great to put the docker image in official aws images. Even better if provide a docker-compose file as well. Then I think we can simply tunnel into containers and ssh to the host from the container! Unless there are serious security concerns.

**Comment by fbertetto** [comment]
@MohMaz exactly! that's how im using it now but the image is pushed to my private docker registry for now, I built that one with this `Dockerfile` so I guess will be a good start to have it one on this repo at least and if we can have it pushed to the official aws images even better!

**Comment by dostiharise** [comment]
The resulting Docker image is super huge. 

It would be amazing we could cleanup the unwanted source files and other compile time dependencies. 

Possibly like a multistage build.

Will try and give it a shot.

**Comment by MohMaz** [comment]
> The resulting Docker image is super huge.
> 
> It would be amazing we could cleanup the unwanted source files and other compile time dependencies.
> 
> Possibly like a multistage build.
> 
> Will try and give it a shot.

Yeah. It's big. I managed to make it smaller using multi-stage build but still the dependencies are big!
It might help to build the dependencies in another folder and remove the sources.

**Comment by dostiharise** [comment]
I have attempted it too, and raised a PR #10.

Waiting for @DavidOgunsAWS or other owner to merge.

**Pull request merged**
